/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // tutorialSidebar: [
  //   {
  //     type: 'autogenerated',
  //     dirName: '.', // '.' means the current docs folder
  //   },
  // ],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    'writing-snapblocks',
    'style-guide',
    {
      type: 'category',
      label: 'For Developers',
      items: [
        {
          type: 'category',
          label: 'API',
          items: ['for-developers/api/api'],
        },
        {
          type: 'category',
          label: 'Plugins',
          items: [
            'for-developers/plugins/discourse',
            'for-developers/plugins/mediawiki',
            'for-developers/plugins/react',
          ]
        },
      ],
    },
  ],
};

export default sidebars;
